[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev"

[deploy]
startCommand = "php artisan storage:link && php artisan view:clear && php artisan cache:clear && php artisan config:clear && php artisan route:clear && php artisan optimize:clear && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 